New-ADGroup -Name "ps_Direction" -GroupScope Global -Path "OU=ps_Utilisateurs,OU=ps_Paris-Ouest,OU=ps_Paris,OU=ps_France,OU=ps_ynovGroup,DC=ynovDomaine,DC=com"
New-ADGroup -Name "ps_Comptabilité" -GroupScope Global -Path "OU=ps_Utilisateurs,OU=ps_Lyon,OU=ps_Est,OU=ps_France,OU=ps_ynovGroup,DC=ynovDomaine,DC=com"
New-ADGroup -Name "ps_Commercial" -GroupScope Global -Path "OU=ps_Utilisateurs,OU=ps_Toulouse,OU=ps_Sud,OU=ps_France,OU=ps_ynovGroup,DC=ynovDomaine,DC=com"
New-ADGroup -Name "ps_Technique" -GroupScope Global -Path "OU=ps_Utilisateurs,OU=ps_Nantes,OU=ps_Ouest,OU=ps_France,OU=ps_ynovGroup,DC=ynovDomaine,DC=com"
New-ADGroup -Name "ps_Communication" -GroupScope Global -Path "OU=ps_Utilisateurs,OU=ps_Aix-en-Provence,OU=ps_Sud,OU=ps_France,OU=ps_ynovGroup,DC=ynovDomaine,DC=com"
New-ADGroup -Name "ps_Service sociale" -GroupScope Global -Path "OU=ps_Utilisateurs,OU=ps_Lille,OU=ps_Nord,OU=ps_France,OU=ps_ynovGroup,DC=ynovDomaine,DC=com"
New-ADGroup -Name "ps_Service Enseignant" -GroupScope Global -Path "OU=ps_Utilisateurs,OU=ps_Casablanca,OU=ps_Internationale,OU=ps_ynovGroup,DC=ynovDomaine,DC=com"
New-ADGroup -Name "ps_Service salle" -GroupScope Global -Path "OU=ps_Utilisateurs,OU=ps_Nice-Sophia,OU=ps_Sud,OU=ps_France,OU=ps_ynovGroup,DC=ynovDomaine,DC=com"
New-ADGroup -Name "ps_Réfectoire" -GroupScope Global -Path "OU=ps_Utilisateurs,OU=ps_Paris-Ouest,OU=ps_Paris,OU=ps_France,OU=ps_ynovGroup,DC=ynovDomaine,DC=com"
New-ADGroup -Name "ps_Service sport" -GroupScope Global -Path "OU=ps_Utilisateurs,OU=ps_Montpellier,OU=ps_Sud,OU=ps_France,OU=ps_ynovGroup,DC=ynovDomaine,DC=com"
